_target_: lightning.pytorch.trainer.trainer.Trainer

# set `1` to train on GPU, `0` to train on CPU only
accelerator: auto
devices: auto
precision: 16

min_epochs: null
max_epochs: 200
reload_dataloaders_every_n_epochs: 0
num_sanity_val_steps: 8
fast_dev_run: false

accumulate_grad_batches: 2
limit_train_batches: 2000
limit_val_batches: 400
log_every_n_steps: 50
