_target_: sat_pred.model.TrainingModule
model: 
  _target_: sat_pred.simvp.SimVP
  _partial_: True
optimizer:
  _target_: sat_pred.model.AdamWReduceLROnPlateau
  lr: 0.0005

num_channels: 11
history_mins: 165
forecast_mins: 180
sample_freq_mins: 15
target_loss: MAE

