_target_: sat_pred.dataloader.SatelliteDataModule

zarr_path:
  - /mnt/disks/nwp_rechunk/sat/2019_nonhrv.zarr
  - /mnt/disks/nwp_rechunk/sat/2020_nonhrv.zarr
  - /mnt/disks/nwp_rechunk/sat/2021_nonhrv.zarr
  #- /mnt/disks/nwp_rechunk/sat/2022_nonhrv.zarr
  - /mnt/disks/nwp_rechunk/sat/2023_nonhrv.zarr

history_mins: 165
forecast_mins: 180
sample_freq_mins: 15

train_period: ["2019-01-01", "2022-01-01"]
val_period: ["2023-01-01", "2023-12-31"]
num_workers: 16
prefetch_factor: 2
batch_size: 1